#!/bin/bash
set -e 

SRC='/Users/roylines/Pictures/New/'
DST='/Users/roylines/Pictures/Mugshot'

echo "importing files from $SRC to $DST..."

exiftool -ext jpg -r -d "$DST/Photos/%Y/%m/%Y%m%d%H%M%S.jpg" "-filename<filemodifydate" $SRC

#echo 'pruning...'
#find $SRC -type d -empty -exec rmdir {} \;
